### ISSUE TITLE
导入本地文件

### ISSUE THREAD

**Issue by planck2003** [kongxiangyiren/hexo-oh-my-live2d#1]
请问怎么导入本地的模型啊

**Comment by kongxiangyiren** [comment]
本地模型放在source目录下

![image](https://github.com/kongxiangyiren/hexo-oh-my-live2d/assets/72970235/31b54980-040e-4ac5-90a5-dac8e55439c7)

_config.yml 的 skip_render 添加模型文件夹 防止编译出错

![image](https://github.com/kongxiangyiren/hexo-oh-my-live2d/assets/72970235/a6e81b7b-8098-46c5-956f-4be8f88793bf)

source 改为'' 使用本地域名
path 为你的model.json路径

```yaml
OhMyLive2d:
  enable: true
  CDN: https://npm.elemecdn.com/oh-my-live2d@0.3.0/dist/index.min.js
  option:
    source: ''
    mobileShow: true # 手机端是否展示
    sayHello: false
    transitionTime: 1000
    models:
      - scale: 1.2
        path: /live2d-widget-model-koharu/assets/koharu.model.json
        x: 0
        'y': 0
        stageStyle:
          backgroundColor: 'rgba(0, 0, 0, 0)'
          width: auto
          height: auto
    tips:
      style:
        width: 230
        height: 120
        offsetX: 0
        offsetY: 90
      idleTips:
        interval: 15000
        # remote: false # 自定义
        remote: false
```

![image](https://github.com/kongxiangyiren/hexo-oh-my-live2d/assets/72970235/ef382963-2615-4487-a2a9-631e9de4f486)
